spring.application.name = Weather-app
weather.api.key = 95b28b5776ec4e2a8e1170527260506
weather.api.url = https://api.weatherapi.com/v1/current.json
weather.api.forecast.url = https://api.weatherapi.com/v1/forecast.json

server.port=8080
