spring.application.name = Weather-app
weather.api.key = Your_API_KEY
weather.api.url = https://api.weatherapi.com/v1/current.json
weather.api.forecast.url = https://api.weatherapi.com/v1/forecast.json

server.port=8080
